---
kind: pkgfile.Build
spec:
  targets:
    - sbc-jetson
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - TOOLS_PREFIX
    - TOOLS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.12.0-alpha.0-51-g3913216
      - name: TOOLS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: TOOLS
        defaultValue: v1.12.0
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
